# Generated by Django 4.2 on 2023-04-21 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_dishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlerecipes',
            name='image',
            field=models.ImageField(null=True, upload_to='upload_images'),
        ),
    ]
