# Generated by Django 4.2 on 2023-04-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_dishes', '0004_steprecipes_titlerecipes_step_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='steprecipes',
            name='image',
            field=models.ImageField(null=True, upload_to='upload_images/steps'),
        ),
    ]
