# Generated by Django 4.2 on 2023-04-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_dishes', '0006_alter_steprecipes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlerecipes',
            name='time',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
