# Generated by Django 4.2 on 2023-04-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_dishes', '0007_alter_titlerecipes_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='steprecipes',
            name='title',
        ),
    ]
