# Generated by Django 4.2 on 2023-04-21 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_dishes', '0010_categories_alter_titlerecipes_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlerecipes',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_recipes', to='recipes_dishes.categories'),
        ),
    ]
